# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50aeb64f16fbaf947b3141537e4b1711e53d6a08fd2f6c24d140f2ca090c780ef0b10f32a165149a9410c33dcae135a940569a870b4735c492cfcec7f76b2413

test:
  secret_key_base: df46c34caf41fa18d9e425a1d685f2ea15e719c554b21822f495b4cca2c8731979add920729f2f9c22f54c9eff5724cca1def02214936a93e308981ba331ec10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
